/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.with.pojo;


import app.with.pojo.serialization.User;
import app.with.pojo.serialization.UserDeserializer;
import app.with.pojo.serialization.UserSerializer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {


        User  u = new User("kim", 1L);

        System.out.println(new App().getGreeting());

        System.out.println(u.getName());

        UserSerializer serial = new UserSerializer();

        byte[] x = serial.serialize(u);

        UserDeserializer deserial = new UserDeserializer();

        User u1 = deserial.deserialize(x);
    }
}
